spring:
  application:
    name: ECommerceAplication
  datasource:
    url: jdbc:mysql://localhost:3306/ECommerceAplication?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Java@2023
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      use-registered-suffix-pattern: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: javatesting406@gmail.com
    password: tcukadgxyxyimnvo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  secret: abc
